### ISSUE TITLE
Offline Emoji

### ISSUE THREAD

**Issue by clsource** [Mogztter/asciidoctor-emoji#10]
Hello, thanks for this wonderful extension. It works superb!.
One idea is having an offline option so emojis are downloaded, using the local image instead of the twemoji url. This would be specially useful when using pdf output.

Thanks again 👍

**Comment by Mogztter** [comment]
Hello @clsource and thanks for your kind words :blush: 
Indeed that's a good idea, I will see what I can do.

**Comment by Mogztter** [comment]
Not sure if I will find the time to do it but if someone wants to give it a try feel free to submit a pull request :+1:

**Comment by Mogztter** [comment]
Fixed in 9b5865a  thanks to @cbergmann 🥇

**Comment by ghost** [comment]
@ggrossetie I guess the README should be updated? The ref to a CDN is a no go for us, so this MR impacts this decision dramatically!

https://github.com/ggrossetie/asciidoctor-emoji?tab=readme-ov-file#how-

**Comment by ggrossetie** [comment]
@qa-alexander-eimer We were also using a CDN before. Are you saying that you don't have access to the CDN during build time?

**Comment by ghost** [comment]
@ggrossetie 
Okay I probably misunderstood the mechanisms of Ascidoctor and the extension.
So please correct me in any false assumptions I have.

To me the README "How?" section gives the impression, that the HTML generated is dependant on a CDN.
To me it looks like the svg is pulled from the CDN when the final result is viewed by the user.
If that is true, it would be a major flaw as I would have hoped, that the svg is inlined into the HTML or the svg is stored in the images folder of the module.

How does this extension work?

I guess the README section "How?" should be written more clear, as it seem not precise enough for me.

**Comment by ggrossetie** [comment]
Before this pull request:

```html
<img src="https://twemoji.maxcdn.com/2/svg/1f41e.svg" alt="beetle" width="24px" height="24px">
```

After this pull request:
```html
<img class="emoji" draggable="false" height="24px" width="24px" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzNiAzNiI+PGNpcmNsZSBmaWxsPSIjMzEzNzNEIiBjeD0iMTgiIGN5PSIxOCIgcj0iMTgiLz48L3N2Zz4=" />
```

The base64 is generated from the CDN but the client (HTML) is not dependent on the CDN.

**Comment by ghost** [comment]
@ggrossetie Ok, understood. Then I did understand the ticket correct.

My point is now, the README.md on the "repo startpage" has this section:
![image](https://github.com/ggrossetie/asciidoctor-emoji/assets/139882236/c4a1ac6c-046c-4524-ae4e-69aad0a5c444)
It appears to me, that the section need an adaption as it doesn't fit the current code, does it?
