### ISSUE TITLE
Possible format bug?

### ISSUE THREAD

**Issue by mitm001** [Mogztter/asciidoctor-emoji#15]
Is this a bug with double colon?

https://github.com/Mogztter/asciidoctor-emoji/blob/59b603952c2f4fbf95b9dddac1416a17ed0e54a3/src/twemoji-map.js#L666

These symbols have broken image when used. I suspect it to be the extra spaces before and after minus signs.
https://github.com/Mogztter/asciidoctor-emoji/blob/59b603952c2f4fbf95b9dddac1416a17ed0e54a3/src/twemoji-map.js#L1651-L1652

https://github.com/Mogztter/asciidoctor-emoji/blob/59b603952c2f4fbf95b9dddac1416a17ed0e54a3/src/twemoji-map.js#L1655-L1661

**Comment by mitm001** [comment]
Broken due to spaces.
https://github.com/Mogztter/asciidoctor-emoji/blob/59b603952c2f4fbf95b9dddac1416a17ed0e54a3/src/twemoji-map.js#L809-L812

**Comment by Mogztter** [comment]
fixed in #16 thanks @mitm001 🎉
